{
 "title": "Ecloytiq Pods Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ecolytiq pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*\", image!=\"\",namespace=\"ecolytiq\", container_name!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Ecolytiq pods CPU Limits/Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\".*\",namespace=\"ecolytiq\",resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\".*\",namespace=\"ecolytiq\",resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ecolytiq pods CPU throttling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=~\".*\", image!=\"\",namespace=\"ecolytiq\", container_name!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Ecolytiq pods Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\".*\", image!=\"\",namespace=\"ecolytiq\", container_name!=\"POD\"}[5m])*0.0000009537) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Ecolytiq pods Memory Limits/Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum((kube_pod_container_resource_requests{pod=~\".*\",namespace=\"ecolytiq\",resource=\"memory\"})*0.0000009537) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum((kube_pod_container_resource_limits{pod=~\".*\",namespace=\"ecolytiq\",resource=\"memory\"})*0.0000009537) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}